name: CI Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test -- --ci --coverage